# Title Here

### Basic Functions on Tensors

An short introduction about PyTorch and about the chosen functions. 
- torch.tensor
- torch.normal
- torch.rand
- torch.tensor.apply()
- torch.tensor.dot()

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.tensor

2x2 tensor with only prime numbers. It is also a differentiable tensor. At the end I also print it out in "console"

In [42]:
# Example 1 - working (change this)
q = torch.tensor([[1, 5], [7, 11]], dtype=torch.float64, requires_grad=True)
print(q)
print(q.dtype)

tensor([[ 1.,  5.],
        [ 7., 11.]], dtype=torch.float64, requires_grad=True)
torch.float64


This is pretty much the same example but i changed the type of tensor, i mean, instead of a float it's a integer

In [40]:
# Example 2 - working
w = torch.tensor([[2, 4],
                  [6,8]], dtype=torch.int64)
print(w)
print(w.dtype)

tensor([[2, 4],
        [6, 8]])
torch.int64


I missed open and close a square parenthesis. For create a NxM matrix, it's necessary be careful with the number of [ and ] you use.

In [39]:
# Example 3 - breaking (to illustrate when it breaks)
w = torch.tensor([2, 4],
                 [6, 8])

TypeError: tensor() takes 1 positional argument but 2 were given

It threw error due to the the lack of [ and ]

## Function 2 - normal

It creates a normal distributed tensor

https://pytorch.org/docs/master/generated/torch.normal.html

normal_(mean=0, std=1, *, generator=None) → Tensor

In [52]:
# Example 1 - working
n = torch.normal(mean=torch.tensor(5.), std=3.)
n

tensor(6.2903)

normal() receives one of:
 * (Tensor mean, Tensor std, *, torch.Generator generator, Tensor out)
 * (Tensor mean, float std, *, torch.Generator generator, Tensor out)
 * (float mean, Tensor std, *, torch.Generator generator, Tensor out)
 * (float mean, float std, tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

In [65]:
# Example 2 - working
n = torch.normal(mean=torch.arange(10.0, 20.0), std=torch.tensor(100))
n

tensor([ -51.4906,   89.0909, -109.3540,  -66.7112, -105.8033,  131.8562,
         190.0289,  183.9491,   -7.3597,   96.6936])

the mean is an `torch.arange` from 10 to 20 and a StandarDev if `torch.tensor` = 100

In [56]:
# Example 3 - breaking (to illustrate when it breaks)
torch.normal(mean=6., std=2.)

TypeError: normal() received an invalid combination of arguments - got (std=float, mean=float, ), but expected one of:
 * (Tensor mean, Tensor std, *, torch.Generator generator, Tensor out)
 * (Tensor mean, float std, *, torch.Generator generator, Tensor out)
 * (float mean, Tensor std, *, torch.Generator generator, Tensor out)
 * (float mean, float std, tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


Invalid input, look details below:

normal() receives one of:
 * (Tensor mean, Tensor std, *, torch.Generator generator, Tensor out)
 * (Tensor mean, float std, *, torch.Generator generator, Tensor out)
 * (float mean, Tensor std, *, torch.Generator generator, Tensor out)
 * (float mean, float std, tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

## Function 3 - torch.rand

rand(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
Returns a tensor filled with random numbers from a uniform distribution
on the interval :math:`[0, 1)`

The shape of the tensor is defined by the variable argument :attr:`size`.

In [74]:
# Example 1 - working
torch.rand(3,6)

tensor([[0.9103, 0.5322, 0.8260, 0.6203, 0.3696, 0.0793],
        [0.7835, 0.1500, 0.4780, 0.2456, 0.7972, 0.0116],
        [0.3904, 0.4413, 0.7999, 0.5684, 0.2761, 0.1261]])

Now, we can see that it creates random matrices

In [77]:
# Example 2 - working
torch.rand(2,3,4)

tensor([[[0.5860, 0.8927, 0.3073, 0.3878],
         [0.9142, 0.9611, 0.1414, 0.7090],
         [0.8073, 0.3822, 0.7522, 0.9995]],

        [[0.0884, 0.8102, 0.4059, 0.6671],
         [0.7207, 0.7422, 0.5005, 0.0813],
         [0.0801, 0.8935, 0.6754, 0.7384]]])

it's created a random tensor

In [89]:
# Example 3 - breaking (to illustrate when it breaks)
torch.rand(2,3, dtype=torch.int)

RuntimeError: _th_uniform_ not supported on CPUType for Int

_th_uniform_ not supported on CPUType for Int

it means that the `dtype` can not be an integer

Closing comments about when to use this function

## Function 4 - apply

Applies the function :attr:`callable` to each element in the tensor, replacing
each element with the value returned by :attr:`callable`.

In [17]:
# Example 1 - working
k = torch.rand(2,3)
print(k)

k.apply_(lambda x:x+1)
k

tensor([[0.6821, 0.0198, 0.7574],
        [0.0461, 0.9894, 0.9080]])


tensor([[1.6821, 1.0198, 1.7574],
        [1.0461, 1.9894, 1.9080]])

Sums 1 to each element of the matrix

In [18]:
# Example 2 - working
def by3(x):
    return x*3

k.apply_(by3)
k

tensor([[5.0464, 3.0593, 5.2722],
        [3.1382, 5.9683, 5.7241]])

it works with user defined functions

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
def wrong(x):
    return str(x)

k.apply_(wrong)
k

TypeError: must be real number, not str

Not all transformations to the elements of the matrices are allowed

## Function 5 - dot

Performs the dot product between 2 VECTORS

In [33]:
# Example 1 - working
t1 = torch.tensor([10, 5, 9])
t2 = torch.tensor([2, 5, 9])

dot_product = t1.dot(t2)
print(dot_product)

tensor(126)


126 = 2*10 +5*5 + 9*9

In [46]:
# Example 2 - working
t3 = torch.rand(3)
t4 = torch.rand(3)

print(t3)
print(t4)

dot_product2 = t3.dot(t4)
dot_product2

tensor([0.4361, 0.8183, 0.1025])
tensor([0.1819, 0.4905, 0.5753])


tensor(0.5397)

Explanation about example

In [23]:
# Example 3 - breaking (to illustrate when it breaks)
t1 = torch.tensor([10, 5])
t2 = torch.tensor([2, 5, 9])

dot_product = t1.dot(t2)
print(dot_product)

RuntimeError: inconsistent tensor size, expected tensor [2] and src [3] to have the same number of elements, but got 2 and 3 elements respectively

The matrices don't have the same size

## Conclusion

I have learnt the basic of PyTorch

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* Official documentation for `torch.normal` https://pytorch.org/docs/master/generated/torch.normal.html

In [3]:
!pip install jovian --upgrade --quiet

In [48]:
import jovian

In [49]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "kevinpulido89/01-tensor-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/kevinpulido89/01-tensor-operations


'https://jovian.ml/kevinpulido89/01-tensor-operations'